require 'simplecov'
SimpleCov.start
require 'minitest/autorun'
require 'minitest/pride'
require 'mocha/minitest'
require './lib/file_writer'
require './lib/format'
require './lib/night_writer'
require './lib/output'
require './lib/translation'
