require 'simplecov'
SimpleCov.start
require 'minitest/autorun'
require 'minitest/pride'
require 'mocha/minitest'
require './lib/file_writer'
require './lib/english_to_braille_format'
require './lib/night_writer'
require './lib/output'
require './lib/translation'
require './lib/braille_to_english_format'
require './lib/night_reader'
